# --- Datasource Postgres ---
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_JDBC_URL}
quarkus.datasource.jdbc.min-size=5
quarkus.datasource.jdbc.max-size=15

# Local defaults for dev/test profile
%dev.quarkus.datasource.username=${DB_USERNAME:postgres}
%dev.quarkus.datasource.password=${DB_PASSWORD:ADMIN}
%dev.quarkus.datasource.jdbc.url=${DB_JDBC_URL:jdbc:postgresql://localhost:5433/api}
%test.quarkus.datasource.username=${DB_USERNAME:postgres}
%test.quarkus.datasource.password=${DB_PASSWORD:ADMIN}
%test.quarkus.datasource.jdbc.url=${DB_JDBC_URL:jdbc:postgresql://localhost:5433/api}

# --- JPA/Hibernate (DEV/TEST) ---
%dev.quarkus.hibernate-orm.schema-management.strategy=update
%dev.quarkus.hibernate-orm.log.sql=true
%test.quarkus.hibernate-orm.schema-management.strategy=update

# --- JWT ---
smallrye.jwt.sign.key.location=${JWT_PRIVATE_KEY_LOCATION}
mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_LOCATION}
mp.jwt.verify.issuer=${JWT_ISSUER:udesc-api}

# Local defaults for dev/test profile
%dev.smallrye.jwt.sign.key.location=${JWT_PRIVATE_KEY_LOCATION:privateKey.pem}
%dev.mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_LOCATION:publicKey.pem}
%test.smallrye.jwt.sign.key.location=${JWT_PRIVATE_KEY_LOCATION:privateKey.pem}
%test.mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_LOCATION:publicKey.pem}

# --- Route security (prod-like default) ---
# Public endpoints in production
quarkus.http.auth.permission.public.paths=/usuario,/usuario/login
quarkus.http.auth.permission.public.policy=permit

# Everything else requires authentication
quarkus.http.auth.permission.protegido.paths=/*
quarkus.http.auth.permission.protegido.policy=authenticated

# --- Dev-only public pages and docs ---
%dev.quarkus.http.auth.permission.public.paths=/,/index.html,/q/swagger-ui,/q/swagger-ui/*,/q/openapi,/usuario,/usuario/login
%dev.quarkus.swagger-ui.always-include=true
%prod.quarkus.swagger-ui.always-include=false

# --- Upload limit (Base64 images) ---
quarkus.http.limits.max-body-size=20M
