# --- Datasource Postgres ---
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=ADMIN
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/api
quarkus.datasource.jdbc.min-size=5
quarkus.datasource.jdbc.max-size=15

# --- JPA/Hibernate (DEV) ---
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# --- JWT ---
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=udesc-api

# --- Segurança de rotas ---
quarkus.http.auth.permission.public.paths=/usuario,/usuario/login

quarkus.http.auth.permission.protegido.policy=authenticated

quarkus.http.limits.max-body-size=20M
